port: "8080"
telegramURL: "https://api.telegram.org/bot"
db:
  login: "vacancy_info_db_user"
  host: "dpg-ch4kc34s3fvjtidlsvag-a.frankfurt-postgres.render.com"
  port: "5432"
  dbName: "vacancy_info_db"
  sslMode: "require"